### ISSUE TITLE
you reversed all updates

### ISSUE THREAD

**Issue by fountainpen** [joackob/nipon-astro-theme#4]
why?

**Comment by joackob** [comment]
Version 6.0.0 of remark-math causes problems when trying to parse markdown files. At the moment only rehype-katex is updated.

**Comment by fountainpen** [comment]
so then you should just have reversed remark math .

so what, now your theme is back to being astro v2 when astro is deep into v3 already

**Comment by joackob** [comment]
Updated all dependencies except remark-math.

**Comment by fountainpen** [comment]
thanks. that's all I wanted.
